
test:
	python3 SAT_test.py

one:
	python3 solve_sudoku.py one_cell.cnf

all:
	python3 solve_sudoku.py all_cells.cnf

cell:
	python3 solve_sudoku.py cell.cnf

rows:
	python3 solve_sudoku.py rows.cnf

both:
	python3 solve_sudoku.py rows_and_cols.cnf

rules:
	python3 solve_sudoku.py rules.cnf

1:
	python3 solve_sudoku.py puzzle1.cnf

2:
	python3 solve_sudoku.py puzzle2.cnf

bonus:
	python3 solve_sudoku.py puzzle_bonus.cnf

hard:
	python3 solve_sudoku.py puzzle_hard.cnf

report:
	pandoc report.md -o report.pdf

